# Automatic Periodic Package Upgrade Provisioning

version: 2

updates:
  - package-ecosystem: npm
    directory: frontend/
    target-branch: main
    versioning-strategy: increase-if-necessary
    schedule:
      interval: weekly
      day: wednesday
      # The time in which GitHub dispatches Dependabot is indeterminate by default
      # Thus, expliciting setting the time ensures consistent operation
      time: "00:00"
    commit-message:
      prefix: "[Dependabot]"
    open-pull-requests-limit: 2

  - package-ecosystem: npm
    directory: "Regenquest GraphQL API/"
    target-branch: main
    versioning-strategy: increase-if-necessary
    schedule:
      interval: weekly
      day: wednesday
      time: "00:00"
    commit-message:
      prefix: "[Dependabot]"
    open-pull-requests-limit: 2
