runtime: nodejs20

handlers:
  # First, serve static files (your React app's build)
  - url: /static
    static_dir: build/static

  # Then, serve the index.html for all other requests
  - url: /.*  # Match any URL path
    static_files: build/index.html
    upload: build/index.html
    http_headers:  # Add this section
      Content-Type: text/html; charset=utf-8

automatic_scaling:
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.75
  min_instances: 1
